language: node_js
dist: trusty
node_js: stable
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-deployer-git --save

before_script:
- git config --global user.name "Ininit"
- git config --global user.email "meininit@gmail.com"
- sed -i "s/__TOKEN__/${__TOKEN__}/" _config.yml

script:
- hexo clean
- hexo generate
- echo "blog.ininit.me" >> public/CNAME
- hexo deploy
branches:
  only:
  - source