# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy blog

on:
  push:
    branches: [ source ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

    - name: use nodejs
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"
        
    - name: init
      run: |
        git config --global user.email "meininit@gmail.com"
        git config --global user.name "Ininit"
        npm install -g yarn
        yarn global add hexo-cli
        yarn add -D hexo-deployer-git
    - name: yarn install
      run: |
        yarn

    - name: deploy
      env:
          TOKEN: ${{secrets.DEPLOY_KEY}} 
      run: |
        sed -i "" "s/\_\_TOKEN\_\_/$TOKEN/" _config.yml
        yarn deploy


